#pragma once

struct lua_State;

/**
 * luafiles.cpp is generated by CMake at compile time.
 * This functions runs .lua files (located in src/) and return 1 if success.
 */
int load_luafiles(lua_State* L);

